companies = ["AACG", "AACI", "AACIU", "AACIW", "AADI", "AAGR", "AAGRW", "AAL", "AAME", "AAOI", "AAON", "AAPL", "ABAT",
             "ABCB", "ABCL", "ABEO", "ABIO", "ABL", "ABLLL", "ABLLW", "ABLV", "ABNB", "ABOS", "ABSI", "ABTS", "ABUS",
             "ABVC", "ABVX", "ACAB", "ACABU", "ACAC", "ACAD", "ACB", "ACBA", "ACBAW", "ACCD", "ACDC", "ACET", "ACGL",
             "ACGLN", "ACGLO", "ACHC", "ACHL", "ACHV", "ACIC", "ACIU", "ACIW", "ACLS", "ACLX", "ACMR", "ACNB", "ACNT",
             "ACON", "ACONW", "ACRS", "ACRV", "ACST", "ACT", "ACTG", "ACVA", "ACXP", "ADAG", "ADAP", "ADBE", "ADD",
             "ADEA",
             "ADI", "ADIL", "ADMA", "ADN", "ADNWW", "ADP", "ADPT", "ADSE", "ADSEW", "ADSK", "ADTH", "ADTHW", "ADTN",
             "ADTX", "ADUS", "ADV", "ADVM", "ADVWW", "ADXN", "AEAE", "AEHL", "AEHR", "AEI", "AEIS", "AEMD", "AENT",
             "AENTW", "AEP", "AERT", "AERTW", "AEYE", "AEZS", "AFAR", "AFARW", "AFBI", "AFCG", "AFJK", "AFMD", "AFRI",
             "AFRIW", "AFRM", "AFYA", "AGAE", "AGBA", "AGBAW", "AGEN", "AGFY", "AGIO", "AGMH", "AGNC", "AGNCL", "AGNCM",
             "AGNCN", "AGNCO", "AGNCP", "AGRI", "AGRIW", "AGYS", "AHCO", "AHG", "AIH", "AIHS", "AILE", "AILEW", "AIMAU",
             "AIMD", "AIMDW", "AIP", "AIRE", "AIRG", "AIRJ", "AIRJW", "AIRS", "AIRT", "AIRTP", "AISP", "AISPW", "AITR",
             "AITRU", "AIXI", "AKAM", "AKAN", "AKBA", "AKLI", "AKRO", "AKTS", "AKTX", "AKYA", "ALAB", "ALAR", "ALBT",
             "ALCE", "ALCO", "ALCY", "ALCYU", "ALCYW", "ALDX", "ALEC", "ALGM", "ALGN", "ALGS", "ALGT", "ALHC", "ALIM",
             "ALKS", "ALKT", "ALLK", "ALLO", "ALLR", "ALLT", "ALNT", "ALNY", "ALOT", "ALPN", "ALPP", "ALRM", "ALRN",
             "ALRS", "ALSA", "ALSAR", "ALSAW", "ALT", "ALTI", "ALTO", "ALTR", "ALVO", "ALVOW", "ALVR", "ALXO", "ALZN",
             "AMAL", "AMAT", "AMBA", "AMCX", "AMD", "AMED", "AMGN", "AMIX", "AMKR", "AMLI", "AMLX", "AMPG", "AMPGW",
             "AMPH", "AMPL", "AMRK", "AMRN", "AMRX", "AMSC", "AMSF", "AMST", "AMSWA", "AMTX", "AMWD", "AMZN", "ANAB",
             "ANDE", "ANEB", "ANGH", "ANGHW", "ANGI", "ANGO", "ANIK", "ANIP", "ANIX", "ANL", "ANNX", "ANSC", "ANSCW",
             "ANSS", "ANTE", "ANTX", "ANY", "AOGO", "AOGOW", "AONC", "AOSL", "AOUT", "APA", "APCX", "APDN", "APEI",
             "APGE",
             "API", "APLD", "APLM", "APLS", "APLT", "APM", "APOG", "APP", "APPF", "APPN", "APPS", "APRE", "APTO",
             "APVO",
             "APWC", "APXI", "APXIW", "APYX", "AQB", "AQMS", "AQST", "AQU", "ARAY", "ARBB", "ARBE", "ARBEW", "ARBK",
             "ARBKL", "ARCB", "ARCC", "ARCT", "ARDX", "AREB", "AREBW", "AREC", "ARGX", "ARHS", "ARKO", "ARKOW", "ARKR",
             "ARLP", "ARM", "AROW", "ARQ", "ARQQ", "ARQQW", "ARQT", "ARRY", "ARTL", "ARTLW", "ARTNA", "ARTW", "ARVN",
             "ARWR", "ARYD", "ASCB", "ASCBR", "ASCBW", "ASLE", "ASLN", "ASMB", "ASML", "ASND", "ASNS", "ASO", "ASPI",
             "ASPS", "ASRT", "ASRV", "ASST", "ASTC", "ASTE", "ASTH", "ASTI", "ASTL", "ASTLW", "ASTR", "ASTS", "ASTSW",
             "ASUR", "ASYS", "ATAI", "ATAT", "ATCOL", "ATEC", "ATER", "ATEX", "ATGL", "ATHA", "ATHE", "ATIF", "ATLC",
             "ATLCL", "ATLCP", "ATLCZ", "ATLO", "ATLX", "ATMC", "ATMCR", "ATMCW", "ATMVR", "ATNF", "ATNFW", "ATNI",
             "ATOM",
             "ATOS", "ATPC", "ATRA", "ATRC", "ATRI", "ATRO", "ATSG", "ATXG", "ATXI", "ATXS", "AUBN", "AUDC", "AUGX",
             "AUID", "AUPH", "AUR", "AURA", "AUROW", "AUTL", "AUUD", "AUUDW", "AUVI", "AUVIP", "AVAH", "AVAV", "AVBP",
             "AVDL", "AVDX", "AVGO", "AVGR", "AVIR", "AVNW", "AVO", "AVPT", "AVPTW", "AVRO", "AVT", "AVTE", "AVTX",
             "AVXL",
             "AWH", "AWIN", "AWINW", "AWRE", "AXDX", "AXGN", "AXNX", "AXON", "AXSM", "AXTI", "AY", "AYRO", "AYTU", "AZ",
             "AZN", "AZPN", "AZTA", "BACK", "BAER", "BAERW", "BAFN", "BAND", "BANF", "BANFP", "BANL", "BANR", "BANX",
             "BAOS", "BASE", "BATRA", "BATRK", "BAYA", "BAYAU", "BBCP", "BBGI", "BBIO", "BBLG", "BBLGW", "BBSI", "BCAB",
             "BCAL", "BCAN", "BCBP", "BCDA", "BCG", "BCGWW", "BCLI", "BCML", "BCOV", "BCOW", "BCPC", "BCRX", "BCSA",
             "BCSAU", "BCSAW", "BCTX", "BCTXW", "BCYC", "BDRX", "BDSX", "BDTX", "BEAM", "BEAT", "BECN", "BEEM", "BELFA",
             "BELFB", "BENF", "BENFW", "BETR", "BFC", "BFI", "BFIIW", "BFIN", "BFRG", "BFRGW", "BFRI", "BFRIW", "BFST",
             "BGC", "BGFV", "BGLC", "BGNE", "BGXX", "BHAT", "BHF", "BHFAL", "BHFAM", "BHFAN", "BHFAO", "BHFAP", "BHRB",
             "BIAF", "BIDU", "BIGC", "BIIB", "BILI", "BIMI", "BIOL", "BIOR", "BIOX", "BIRD", "BITF", "BIVI", "BJDX",
             "BJRI", "BKHA", "BKHAR", "BKHAU", "BKNG", "BKR", "BKYI", "BL", "BLAC", "BLACR", "BLACU", "BLBD", "BLBX",
             "BLDE", "BLDEW", "BLDP", "BLEU", "BLFS", "BLFY", "BLIN", "BLKB", "BLMN", "BLNK", "BLRX", "BLTE", "BLUE",
             "BLZE", "BMBL", "BMEA", "BMR", "BMRA", "BMRC", "BMRN", "BNAI", "BNAIW", "BNGO", "BNIX", "BNOX", "BNR",
             "BNRG",
             "BNTC", "BNTX", "BNZI", "BNZIW", "BOCN", "BOF", "BOKF", "BOLD", "BOLT", "BON", "BOOM", "BOSC", "BOTJ",
             "BOWN",
             "BOWNU", "BOXL", "BPMC", "BPOP", "BPOPM", "BPRN", "BPTH", "BPYPM", "BPYPN", "BPYPO", "BPYPP", "BRAC",
             "BRAG",
             "BREA", "BREZ", "BREZR", "BREZW", "BRFH", "BRID", "BRKH", "BRKHU", "BRKHW", "BRKL", "BRKR", "BRLS",
             "BRLSW",
             "BRLT", "BRNS", "BROG", "BROGW", "BRP", "BRSH", "BRSHW", "BRTX", "BRY", "BRZE", "BSBK", "BSET", "BSFC",
             "BSGM", "BSRR", "BSVN", "BSY", "BTAI", "BTBD", "BTBT", "BTCS", "BTCT", "BTCTW", "BTCY", "BTDR", "BTM",
             "BTMD",
             "BTMWW", "BTOC", "BTOG", "BTSG", "BTSGU", "BUJA", "BUJAR", "BUJAW", "BUSE", "BVFL", "BVS", "BWAQ", "BWAQW",
             "BWAY", "BWB", "BWBBP", "BWEN", "BWFG", "BWMN", "BWMX", "BYFC", "BYND", "BYNO", "BYNOW", "BYRN", "BYSI",
             "BYU", "BZ", "BZFD", "BZFDW", "BZUN", "CAAS", "CABA", "CAC", "CACC", "CACO", "CADL", "CAKE", "CALB",
             "CALC",
             "CALM", "CALT", "CAMP", "CAMT", "CAN", "CAPR", "CAPT", "CAPTW", "CAR", "CARA", "CARE", "CARG", "CARM",
             "CART",
             "CARV", "CASH", "CASI", "CASS", "CASY", "CATC", "CATY", "CAUD", "CBAN", "CBAT", "CBFV", "CBNK", "CBRG",
             "CBRL", "CBSH", "CBUS", "CCAP", "CCB", "CCBG", "CCCC", "CCCS", "CCD", "CCEP", "CCG", "CCGWW", "CCIXU",
             "CCLD",
             "CCLDO", "CCLDP", "CCNE", "CCNEP", "CCOI", "CCRN", "CCSI", "CCTG", "CCTS", "CCTSW", "CDAQ", "CDIO",
             "CDIOW",
             "CDLX", "CDMO", "CDNA", "CDNS", "CDRO", "CDROW", "CDT", "CDTG", "CDTX", "CDW", "CDXC", "CDXS", "CDZI",
             "CDZIP", "CEAD", "CECO", "CEG", "CELC", "CELH", "CELU", "CELUW", "CELZ", "CENN", "CENT", "CENTA", "CENX",
             "CERE", "CERO", "CEROW", "CERS", "CERT", "CETU", "CETX", "CETY", "CEVA", "CFB", "CFBK", "CFFI", "CFFN",
             "CFFS", "CFLT", "CFSB", "CG", "CGABL", "CGBD", "CGBDL", "CGC", "CGEM", "CGEN", "CGNT", "CGNX", "CGO",
             "CGON",
             "CGTX", "CHCI", "CHCO", "CHDN", "CHEF", "CHEK", "CHI", "CHK", "CHKEL", "CHKEW", "CHKEZ", "CHKP", "CHMG",
             "CHNR", "CHR", "CHRD", "CHRS", "CHRW", "CHSCL", "CHSCM", "CHSCN", "CHSCO", "CHSCP", "CHSN", "CHTR", "CHUY",
             "CHW", "CHX", "CHY", "CIFR", "CIFRW", "CIGI", "CINF", "CING", "CINGW", "CISO", "CISS", "CITE", "CITEW",
             "CIVB", "CJET", "CJJD", "CKPT", "CLAR", "CLBK", "CLBT", "CLBTW", "CLDX", "CLEU", "CLFD", "CLGN", "CLIR",
             "CLLS", "CLMB", "CLMT", "CLNE", "CLNN", "CLNNW", "CLOE", "CLOV", "CLPS", "CLPT", "CLRB", "CLRC", "CLRCW",
             "CLRO", "CLSD", "CLSK", "CLST", "CLVR", "CLVRW", "CLWT", "CMAX", "CMBM", "CMCA", "CMCO", "CMCSA", "CMCT",
             "CME", "CMLS", "CMMB", "CMND", "CMPO", "CMPOW", "CMPR", "CMPS", "CMPX", "CMRX", "CMTL", "CNDT", "CNET",
             "CNEY", "CNFR", "CNFRZ", "CNGL", "CNGLU", "CNGLW", "CNOB", "CNOBP", "CNSL", "CNSP", "CNTA", "CNTB", "CNTG",
             "CNTX", "CNTY", "CNVS", "CNXC", "CNXN", "COCH", "COCHW", "COCO", "COCP", "CODA", "CODX", "COEP", "COFS",
             "COGT", "COHU", "COIN", "COKE", "COLB", "COLL", "COLM", "COMM", "CONN", "COO", "COOL", "COOLW", "COOP",
             "COOT", "COOTW", "CORT", "CORZ", "CORZW", "CORZZ", "COSM", "COST", "COYA", "CPBI", "CPHC", "CPIX", "CPLP",
             "CPOP", "CPRT", "CPRX", "CPSH", "CPSS", "CPTN", "CPTNW", "CPZ", "CRAI", "CRBP", "CRBU", "CRCT", "CRDF",
             "CRDL", "CRDO", "CREG", "CRESW", "CRESY", "CREV", "CREVW", "CREX", "CRGO", "CRGOW", "CRGX", "CRIS", "CRKN",
             "CRMD", "CRML", "CRMT", "CRNC", "CRNT", "CRNX", "CRON", "CROX", "CRSP", "CRSR", "CRTO", "CRUS", "CRVL",
             "CRVO", "CRVS", "CRWD", "CRWS", "CSBR", "CSCO", "CSGP", "CSGS", "CSIQ", "CSLM", "CSLMW", "CSLR", "CSLRW",
             "CSPI", "CSQ", "CSSE", "CSSEL", "CSSEN", "CSSEP", "CSTE", "CSTL", "CSWC", "CSWCZ", "CSWI", "CSX", "CTAS",
             "CTBI", "CTCX", "CTCXW", "CTHR", "CTKB", "CTLP", "CTMX", "CTNM", "CTNT", "CTRM", "CTRN", "CTSH", "CTSO",
             "CTXR", "CUBA", "CUE", "CULL", "CURI", "CURIW", "CUTR", "CVAC", "CVBF", "CVCO", "CVGI", "CVGW", "CVII",
             "CVIIU", "CVIIW", "CVKD", "CVLG", "CVLT", "CVLY", "CVRX", "CVV", "CWBC", "CWCO", "CWD", "CWST", "CXAI",
             "CXAIW", "CXDO", "CYBR", "CYCC", "CYCCP", "CYCN", "CYN", "CYRX", "CYTH", "CYTHW", "CYTK", "CYTO", "CZFS",
             "CZNC", "CZR", "CZWI", "DADA", "DAIO", "DAKT", "DALN", "DARE", "DASH", "DATS", "DATSW", "DAVE", "DAVEW",
             "DAWN", "DBGI", "DBGIW", "DBVT", "DBX", "DCBO", "DCGO", "DCOM", "DCOMP", "DCPH", "DCTH", "DDI", "DDOG",
             "DECA", "DECAU", "DECAW", "DENN", "DERM", "DFLI", "DFLIW", "DGHI", "DGICA", "DGICB", "DGII", "DGLY", "DH",
             "DHAC", "DHACW", "DHAI", "DHC", "DHCNI", "DHCNL", "DHIL", "DIBS", "DIOD", "DIST", "DISTR", "DISTW", "DJCO",
             "DJT", "DJTWW", "DKNG", "DLHC", "DLO", "DLPN", "DLTH", "DLTR", "DMAC", "DMLP", "DMRC", "DMTK", "DNLI",
             "DNTH",
             "DNUT", "DOCU", "DOGZ", "DOMH", "DOMO", "DOOO", "DORM", "DOX", "DOYU", "DPCS", "DPRO", "DRCT", "DRIO",
             "DRMA",
             "DRRX", "DRS", "DRTS", "DRTSW", "DRUG", "DRVN", "DSGN", "DSGR", "DSGX", "DSP", "DSWL", "DTCK", "DTI",
             "DTIL",
             "DTSS", "DTST", "DTSTW", "DUO", "DUOL", "DUOT", "DVAX", "DWSN", "DXCM", "DXLG", "DXPE", "DXR", "DXYN",
             "DYAI",
             "DYCQ", "DYCQR", "DYCQU", "DYN", "DYNT", "DZSI", "EA", "EAST", "EBAY", "EBC", "EBMT", "EBON", "EBTC",
             "ECBK",
             "ECDA", "ECDAW", "ECOR", "ECPG", "ECX", "EDAP", "EDBL", "EDBLW", "EDIT", "EDRY", "EDSA", "EDTK", "EDUC",
             "EEFT", "EEIQ", "EFOI", "EFSC", "EFSCP", "EFTR", "EFTRW", "EGAN", "EGBN", "EGHT", "EGIO", "EGRX", "EH",
             "EHTH", "EJH", "EKSO", "ELAB", "ELBM", "ELDN", "ELEV", "ELSE", "ELTK", "ELTX", "ELUT", "ELVA", "ELVN",
             "ELWS",
             "ELYM", "EM", "EMBC", "EMCG", "EMCGR", "EMKR", "EML", "EMLD", "EMLDW", "ENG", "ENGN", "ENGNW", "ENLT",
             "ENLV",
             "ENPH", "ENSC", "ENSG", "ENTA", "ENTG", "ENTX", "ENVB", "ENVX", "EOLS", "EOSE", "EOSEW", "EPIX", "EPOW",
             "EPRX", "EPSN", "EQ", "EQIX", "ERAS", "ERIC", "ERIE", "ERII", "ERNA", "ESCA", "ESEA", "ESGL", "ESGLW",
             "ESGR",
             "ESGRO", "ESGRP", "ESHA", "ESHAR", "ESLA", "ESLAW", "ESLT", "ESOA", "ESPR", "ESQ", "ESSA", "ESTA", "ETNB",
             "ETON", "ETSY", "EU", "EUDA", "EVAX", "EVBG", "EVCM", "EVER", "EVGN", "EVGO", "EVGOW", "EVGR", "EVGRW",
             "EVLV", "EVLVW", "EVO", "EVOK", "EVRG", "EVTV", "EWBC", "EWCZ", "EWTX", "EXAI", "EXAS", "EXC", "EXEL",
             "EXFY",
             "EXLS", "EXPE", "EXPI", "EXPO", "EXTR", "EYE", "EYEN", "EYPT", "EZFL", "EZGO", "EZPW", "FA", "FAAS",
             "FAASW",
             "FAMI", "FANG", "FANH", "FARM", "FARO", "FAST", "FAT", "FATBB", "FATBP", "FATBW", "FATE", "FBIO", "FBIOP",
             "FBIZ", "FBLG", "FBMS", "FBNC", "FBRX", "FBYD", "FBYDW", "FCAP", "FCBC", "FCCO", "FCEL", "FCFS", "FCNCA",
             "FCNCO", "FCNCP", "FCUV", "FDBC", "FDMT", "FDUS", "FEAM", "FEBO", "FEIM", "FELE", "FEMY", "FENC", "FER",
             "FEXD", "FEXDW", "FFBC", "FFIC", "FFIE", "FFIEW", "FFIN", "FFIV", "FFNW", "FGBI", "FGBIP", "FGEN", "FGF",
             "FGFPP", "FGI", "FGIWW", "FHB", "FHLT", "FHLTW", "FHTX", "FIBK", "FINW", "FIP", "FISI", "FITB", "FITBI",
             "FITBO", "FITBP", "FIVE", "FIVN", "FIZZ", "FKWL", "FLEX", "FLFV", "FLFVR", "FLGC", "FLGT", "FLIC", "FLJ",
             "FLL", "FLNC", "FLNT", "FLUX", "FLWS", "FLXS", "FLYW", "FMAO", "FMBH", "FMNB", "FMST", "FNCB", "FNCH",
             "FNGR",
             "FNKO", "FNLC", "FNVT", "FNVTW", "FNWB", "FNWD", "FOLD", "FONR", "FORA", "FORD", "FORL", "FORM", "FORR",
             "FORTY", "FOSL", "FOSLL", "FOX", "FOXA", "FOXF", "FPAY", "FRAF", "FRBA", "FREE", "FRES", "FRGT", "FRHC",
             "FRLA", "FRLAW", "FRME", "FRMEP", "FROG", "FRPH", "FRPT", "FRSH", "FRST", "FRSX", "FRZA", "FSBC", "FSBW",
             "FSEA", "FSFG", "FSLR", "FSTR", "FSV", "FTAI", "FTAIM", "FTAIN", "FTAIO", "FTAIP", "FTCI", "FTDR", "FTEK",
             "FTEL", "FTFT", "FTHM", "FTII", "FTIIU", "FTLF", "FTNT", "FTRE", "FUFU", "FUFUW", "FULC", "FULT", "FULTP",
             "FUNC", "FUND", "FUSB", "FUSN", "FUTU", "FVCB", "FWBI", "FWONA", "FWONK", "FWRD", "FWRG", "FXNC", "FYBR",
             "GABC", "GAIA", "GAIN", "GAINL", "GAINN", "GAINZ", "GALT", "GAMB", "GAMC", "GAMCW", "GAME", "GAN", "GANX",
             "GAQ", "GASS", "GATE", "GBBK", "GBBKR", "GBBKW", "GBDC", "GBIO", "GBNY", "GCBC", "GCMG", "GCMGW", "GCT",
             "GCTK", "GDC", "GDEN", "GDEV", "GDHG", "GDRX", "GDS", "GDST", "GDSTW", "GDTC", "GDYN", "GECC", "GECCI",
             "GECCM", "GECCO", "GECCZ", "GEG", "GEGGL", "GEHC", "GEN", "GENE", "GENK", "GEOS", "GERN", "GEVO", "GFAI",
             "GFAIW", "GFS", "GGAL", "GGR", "GGROW", "GH", "GHIX", "GHIXW", "GHRS", "GHSI", "GIFI", "GIGM", "GIII",
             "GILD",
             "GILT", "GIPR", "GIPRW", "GLAC", "GLACU", "GLAD", "GLADZ", "GLBE", "GLBS", "GLBZ", "GLDD", "GLLI", "GLLIR",
             "GLMD", "GLNG", "GLPG", "GLPI", "GLRE", "GLSI", "GLST", "GLTO", "GLUE", "GLYC", "GMAB", "GMFI", "GMFIW",
             "GMGI", "GMM", "GNFT", "GNLN", "GNLX", "GNPX", "GNSS", "GNTA", "GNTX", "GO", "GOCO", "GODN", "GOEV",
             "GOEVW",
             "GOGL", "GOGO", "GOOD", "GOODN", "GOODO", "GOOG", "GOOGL", "GORV", "GOSS", "GOVX", "GOVXW", "GP", "GPAC",
             "GPACW", "GPAK", "GPATU", "GPCR", "GPRE", "GPRO", "GRAB", "GRABW", "GRDI", "GRDIW", "GREE", "GREEL",
             "GRFS",
             "GRI", "GRIN", "GRNQ", "GROM", "GROW", "GRPN", "GRRR", "GRRRW", "GRTS", "GRTX", "GRVY", "GRWG", "GRYP",
             "GSBC", "GSHD", "GSIT", "GSIW", "GSM", "GSMGW", "GSUN", "GT", "GTAC", "GTACW", "GTBP", "GTEC", "GTHX",
             "GTI",
             "GTIM", "GTLB", "GTX", "GURE", "GUTS", "GV", "GVH", "GVP", "GWAV", "GWRS", "GXAI", "GYRE", "GYRO", "HA",
             "HAFC", "HAIA", "HAIN", "HALO", "HAO", "HAS", "HAYN", "HBAN", "HBANL", "HBANM", "HBANP", "HBCP", "HBIO",
             "HBNC", "HBT", "HCAT", "HCKT", "HCM", "HCP", "HCSG", "HCTI", "HCVI", "HCVIU", "HCWB", "HDSN", "HEAR",
             "HEES",
             "HELE", "HEPA", "HEPS", "HFBL", "HFFG", "HFWA", "HGAS", "HGASW", "HGBL", "HHGC", "HHS", "HIBB", "HIFS",
             "HIHO", "HIMX", "HITI", "HIVE", "HKIT", "HLIT", "HLMN", "HLNE", "HLP", "HLTH", "HLVX", "HLXB", "HMNF",
             "HMST",
             "HNNA", "HNNAZ", "HNRG", "HNST", "HNVR", "HOFT", "HOFV", "HOFVW", "HOLI", "HOLO", "HOLOW", "HOLX", "HON",
             "HONE", "HOOD", "HOOK", "HOPE", "HOTH", "HOUR", "HOVNP", "HOVR", "HOVRW", "HOWL", "HPCO", "HPH", "HPK",
             "HPKEW", "HQI", "HQY", "HRMY", "HROW", "HROWL", "HROWM", "HRTX", "HRYU", "HRZN", "HSAI", "HSCS", "HSCSW",
             "HSDT", "HSIC", "HSII", "HSON", "HSPO", "HSPOU", "HST", "HSTM", "HTBI", "HTBK", "HTCR", "HTHT", "HTIA",
             "HTIBP", "HTLD", "HTLF", "HTLFP", "HTOO", "HTOOW", "HTZ", "HTZWW", "HUBC", "HUBCW", "HUBCZ", "HUBG",
             "HUDA",
             "HUDAU", "HUDI", "HUGE", "HUIZ", "HUMA", "HUMAW", "HURC", "HURN", "HUT", "HWBK", "HWC", "HWCPZ", "HWH",
             "HWKN", "HYFM", "HYMC", "HYMCL", "HYMCW", "HYPR", "HYW", "HYZN", "HYZNW", "IAC", "IART", "IAS", "IBAC",
             "IBACR", "IBCP", "IBEX", "IBKR", "IBOC", "IBRX", "IBTX", "ICAD", "ICCC", "ICCH", "ICCM", "ICCT", "ICFI",
             "ICG", "ICHR", "ICLK", "ICLR", "ICMB", "ICU", "ICUCW", "ICUI", "IDAI", "IDCC", "IDEX", "IDN", "IDXX",
             "IDYA",
             "IEP", "IESC", "IFBD", "IFRX", "IGIC", "IGMS", "IGTA", "IGTAR", "IGTAU", "IGTAW", "IHRT", "III", "IIIV",
             "IINN", "IINNW", "IKNA", "IKT", "ILAG", "ILMN", "ILPT", "IMAB", "IMAQ", "IMAQU", "IMCC", "IMCR", "IMKTA",
             "IMMP", "IMMR", "IMMX", "IMNM", "IMNN", "IMOS", "IMPP", "IMPPP", "IMRN", "IMRX", "IMTE", "IMTX", "IMTXW",
             "IMUX", "IMVT", "IMXI", "INAB", "INAQ", "INAQW", "INBK", "INBKZ", "INBS", "INBX", "INCR", "INCY", "INDB",
             "INDI", "INDP", "INDV", "INFN", "INGN", "INHD", "INKT", "INM", "INMB", "INMD", "INNV", "INO", "INOD",
             "INSE",
             "INSG", "INSM", "INTA", "INTC", "INTE", "INTG", "INTJ", "INTR", "INTS", "INTU", "INTZ", "INVA", "INVE",
             "INVO", "INVZ", "INVZW", "INZY", "IOBT", "IONM", "IONR", "IONS", "IOSP", "IOVA", "IPA", "IPAR", "IPDN",
             "IPGP", "IPHA", "IPSC", "IPW", "IPWR", "IPX", "IPXX", "IPXXW", "IQ", "IRAA", "IRAAW", "IRBT", "IRDM",
             "IREN",
             "IRIX", "IRMD", "IROH", "IROHR", "IROHU", "IROHW", "IRON", "IROQ", "IRTC", "IRWD", "ISPC", "ISPO", "ISPOW",
             "ISPR", "ISRG", "ISRL", "ISRLW", "ISSC", "ISTR", "ISUN", "ITCI", "ITI", "ITIC", "ITOS", "ITRI", "ITRM",
             "ITRN", "IVA", "IVAC", "IVCA", "IVCAW", "IVCB", "IVCBW", "IVCP", "IVCPW", "IVDA", "IVDAW", "IVP", "IVVD",
             "IXAQ", "IXHL", "IZEA", "IZM", "JACK", "JAGX", "JAKK", "JAMF", "JAN", "JANX", "JAZZ", "JBHT", "JBLU",
             "JBSS",
             "JCSE", "JCTCF", "JD", "JEWL", "JFBR", "JFBRW", "JFIN", "JFU", "JG", "JJSF", "JKHY", "JL", "JMSB", "JNVR",
             "JOUT", "JRSH", "JRVR", "JSM", "JSPR", "JSPRW", "JTAI", "JTAIW", "JTAIZ", "JUNE", "JVA", "JVSA", "JVSAR",
             "JWEL", "JXJT", "JYD", "JYNT", "JZ", "JZXN", "KA", "KACLR", "KACLW", "KALA", "KALU", "KALV", "KARO",
             "KAVL",
             "KC", "KDP", "KE", "KELYA", "KELYB", "KEQU", "KFFB", "KFRC", "KGEI", "KHC", "KIDS", "KINS", "KIRK", "KITT",
             "KITTW", "KLAC", "KLIC", "KLTR", "KLXE", "KMDA", "KNDI", "KNSA", "KOD", "KOPN", "KOSS", "KPLT", "KPLTW",
             "KPRX", "KPTI", "KRKR", "KRMD", "KRNL", "KRNLW", "KRNT", "KRNY", "KRON", "KROS", "KRRO", "KRT", "KRUS",
             "KRYS", "KSCP", "KSPI", "KTCC", "KTOS", "KTRA", "KTTA", "KTTAW", "KURA", "KVAC", "KVACU", "KVACW", "KVHI",
             "KWE", "KXIN", "KYMR", "KYTX", "KZIA", "KZR", "LAB", "LABP", "LAES", "LAKE", "LAMR", "LANC", "LAND",
             "LANDM",
             "LANDO", "LANDP", "LARK", "LASE", "LASR", "LATG", "LAUR", "LAZR", "LBAI", "LBPH", "LBRDA", "LBRDK",
             "LBRDP",
             "LBTYA", "LBTYB", "LBTYK", "LCFY", "LCID", "LCNB", "LCUT", "LDTC", "LDTCW", "LDWY", "LE", "LECO", "LEDS",
             "LEE", "LEGH", "LEGN", "LENZ", "LESL", "LEXX", "LEXXW", "LFCR", "LFLY", "LFLYW", "LFMD", "LFMDP", "LFST",
             "LFUS", "LFVN", "LFWD", "LGCB", "LGCL", "LGHL", "LGHLW", "LGIH", "LGMK", "LGND", "LGO", "LGVN", "LI",
             "LICN",
             "LIDR", "LIDRW", "LIFE", "LIFW", "LIFWW", "LIFWZ", "LILA", "LILAK", "LILM", "LILMW", "LIN", "LINC", "LIND",
             "LINK", "LION", "LIPO", "LIQT", "LITE", "LITM", "LIVE", "LIVN", "LIXT", "LIXTW", "LKCO", "LKFN", "LKQ",
             "LLYVA", "LLYVK", "LMAT", "LMB", "LMFA", "LMNR", "LNKB", "LNSR", "LNT", "LNTH", "LNW", "LNZA", "LNZAW",
             "LOAN", "LOBO", "LOCO", "LOGC", "LOGI", "LOOP", "LOPE", "LOT", "LOTWW", "LOVE", "LPCN", "LPLA", "LPRO",
             "LPSN", "LPTH", "LPTX", "LQDA", "LQDT", "LQR", "LRCX", "LRE", "LRFC", "LRHC", "LRMR", "LSAK", "LSBK",
             "LSCC",
             "LSDI", "LSEA", "LSEAW", "LSTA", "LSTR", "LSXMA", "LSXMB", "LSXMK", "LTBR", "LTRN", "LTRX", "LTRY",
             "LTRYW",
             "LUCD", "LUCY", "LUCYW", "LULU", "LUMO", "LUNA", "LUNG", "LUNR", "LUNRW", "LUXH", "LUXHP", "LVLU", "LVO",
             "LVRO", "LVTX", "LWAY", "LWLG", "LX", "LXEH", "LXEO", "LXRX", "LYEL", "LYFT", "LYRA", "LYT", "LYTS", "LZ",
             "MACA", "MACAW", "MACK", "MAMA", "MAMO", "MANH", "MAPS", "MAPSW", "MAQC", "MAR", "MARA", "MARPS", "MARX",
             "MARXR", "MARXU", "MASI", "MASS", "MAT", "MATH", "MATW", "MAXN", "MAYS", "MBCN", "MBIN", "MBINM", "MBINN",
             "MBINO", "MBIO", "MBLY", "MBNKP", "MBOT", "MBRX", "MBUU", "MBWM", "MCAA", "MCAG", "MCBC", "MCBS", "MCFT",
             "MCHP", "MCHX", "MCRB", "MCRI", "MCVT", "MDAI", "MDAIW", "MDB", "MDBH", "MDGL", "MDIA", "MDJH", "MDLZ",
             "MDRR", "MDRRP", "MDWD", "MDXG", "MDXH", "ME", "MEDP", "MEDS", "MEGL", "MEIP", "MELI", "MEOH", "MERC",
             "MESA",
             "MESO", "META", "METC", "METCB", "METCL", "MFH", "MFI", "MFIC", "MFICL", "MFIN", "MGEE", "MGIC", "MGIH",
             "MGNI", "MGNX", "MGOL", "MGPI", "MGRC", "MGRM", "MGRX", "MGTX", "MGX", "MGYR", "MHLD", "MHUA", "MICS",
             "MIDD",
             "MIGI", "MIND", "MINDP", "MINM", "MIRA", "MIRM", "MIST", "MITK", "MKSI", "MKTW", "MKTX", "MLAB", "MLCO",
             "MLEC", "MLECW", "MLGO", "MLKN", "MLTX", "MLYS", "MMAT", "MMLP", "MMSI", "MMV", "MMVWW", "MMYT", "MNDO",
             "MNDR", "MNDY", "MNKD", "MNMD", "MNOV", "MNPR", "MNRO", "MNSB", "MNSBP", "MNST", "MNTK", "MNTS", "MNTSW",
             "MNTX", "MNY", "MNYWW", "MOB", "MOBX", "MOBXW", "MODD", "MODV", "MOFG", "MOGO", "MOLN", "MOMO", "MOND",
             "MOR",
             "MORF", "MORN", "MOVE", "MPAA", "MPB", "MPWR", "MQ", "MRAI", "MRAM", "MRBK", "MRCC", "MRCY", "MREO",
             "MRIN",
             "MRKR", "MRM", "MRNA", "MRNO", "MRNOW", "MRNS", "MRSN", "MRTN", "MRUS", "MRVI", "MRVL", "MRX", "MSAI",
             "MSBI",
             "MSBIP", "MSEX", "MSFT", "MSGM", "MSS", "MSTR", "MTC", "MTCH", "MTEK", "MTEM", "MTEN", "MTEX", "MTLS",
             "MTRX",
             "MTSI", "MTTR", "MU", "MULN", "MURA", "MVBF", "MVIS", "MVST", "MVSTW", "MXCT", "MXL", "MYFW", "MYGN",
             "MYMD",
             "MYNA", "MYNZ", "MYPS", "MYPSW", "MYRG", "MYSZ", "NA", "NAAS", "NAII", "NAMS", "NAMSW", "NAOV", "NARI",
             "NATH", "NATR", "NAUT", "NAVI", "NB", "NBBK", "NBIX", "NBN", "NBST", "NBSTW", "NBTB", "NBTX", "NCI",
             "NCMI",
             "NCNA", "NCNC", "NCNO", "NCPL", "NCRA", "NCSM", "NCTY", "NDAQ", "NDLS", "NDRA", "NDSN", "NECB", "NEGG",
             "NEO",
             "NEOG", "NEON", "NEOV", "NEOVW", "NEPH", "NERV", "NETD", "NETDU", "NETDW", "NEWT", "NEWTI", "NEWTL",
             "NEWTZ",
             "NEXI", "NEXN", "NEXT", "NFBK", "NFE", "NFLX", "NGNE", "NHTC", "NICE", "NICK", "NIOBW", "NISN", "NITO",
             "NIU",
             "NIVF", "NIVFW", "NKGN", "NKGNW", "NKLA", "NKSH", "NKTR", "NKTX", "NLSP", "NLSPW", "NMFC", "NMFCZ", "NMHI",
             "NMIH", "NMRA", "NMRK", "NMTC", "NN", "NNAG", "NNAGR", "NNAGU", "NNAVW", "NNBR", "NNDM", "NNE", "NNOX",
             "NODK", "NOTV", "NOVT", "NOVV", "NOVVU", "NOVVW", "NPAB", "NPABW", "NPCE", "NRBO", "NRC", "NRDS", "NRIM",
             "NRIX", "NRSN", "NRSNW", "NRXP", "NRXPW", "NSIT", "NSPR", "NSSC", "NSTS", "NSYS", "NTAP", "NTBL", "NTCT",
             "NTES", "NTGR", "NTIC", "NTLA", "NTNX", "NTRA", "NTRB", "NTRBW", "NTRP", "NTRS", "NTRSO", "NTWK", "NUKK",
             "NUKKW", "NURO", "NUTX", "NUVL", "NUVO", "NUVOW", "NUWE", "NUZE", "NVAC", "NVAX", "NVCR", "NVCT", "NVDA",
             "NVEC", "NVEE", "NVEI", "NVFY", "NVMI", "NVNI", "NVNO", "NVOS", "NVTS", "NVVE", "NVVEW", "NVX", "NWBI",
             "NWE",
             "NWFL", "NWGL", "NWL", "NWLI", "NWPX", "NWS", "NWSA", "NWTN", "NWTNW", "NXGL", "NXGLW", "NXL", "NXLIW",
             "NXPI", "NXPL", "NXPLW", "NXST", "NXT", "NXTC", "NXTT", "NXU", "NYAX", "NYMT", "NYMTL", "NYMTM", "NYMTN",
             "NYMTZ", "NYXH", "OABI", "OABIW", "OAKU", "OAKUW", "OB", "OBIO", "OBLG", "OBT", "OCAX", "OCAXU", "OCC",
             "OCCI", "OCCIN", "OCCIO", "OCEA", "OCEAW", "OCFC", "OCFCP", "OCG", "OCGN", "OCS", "OCSAW", "OCSL", "OCTO",
             "OCUL", "OCUP", "OCX", "ODD", "ODFL", "ODP", "OESX", "OFIX", "OFLX", "OFS", "OGI", "OKTA", "OKYO", "OLB",
             "OLED", "OLK", "OLLI", "OLMA", "OLPX", "OM", "OMAB", "OMCL", "OMER", "OMEX", "OMGA", "OMH", "OMIC", "ON",
             "ONB", "ONBPO", "ONBPP", "ONCO", "ONCT", "ONCY", "ONDS", "ONEW", "ONFO", "ONFOW", "ONMD", "ONMDW", "ONVO",
             "ONYX", "OP", "OPAL", "OPBK", "OPCH", "OPEN", "OPGN", "OPHC", "OPI", "OPINL", "OPK", "OPOF", "OPRA",
             "OPRT",
             "OPRX", "OPT", "OPTN", "OPTX", "OPTXW", "OPXS", "ORGN", "ORGNW", "ORGO", "ORGS", "ORIC", "ORLY", "ORMP",
             "ORRF", "OSBC", "OSIS", "OSPN", "OSS", "OST", "OSUR", "OSW", "OTEX", "OTLK", "OTLY", "OTRK", "OTTR",
             "OVBC",
             "OVID", "OVLY", "OXBR", "OXBRW", "OXLC", "OXLCL", "OXLCM", "OXLCN", "OXLCO", "OXLCP", "OXLCZ", "OXSQ",
             "OXSQG", "OXSQZ", "OZK", "OZKAP", "PAA", "PACB", "PAGP", "PAHC", "PAL", "PALI", "PALT", "PANL", "PANW",
             "PARA", "PARAA", "PASG", "PATK", "PAVM", "PAVMZ", "PAVS", "PAX", "PAYO", "PAYOW", "PAYS", "PAYX", "PBBK",
             "PBFS", "PBHC", "PBM", "PBMWW", "PBPB", "PBYI", "PCAR", "PCB", "PCH", "PCRX", "PCSA", "PCT", "PCTTW",
             "PCTY",
             "PCVX", "PCYO", "PDCO", "PDD", "PDEX", "PDFS", "PDLB", "PDSB", "PDYN", "PDYNW", "PEBK", "PEBO", "PECO",
             "PEGA", "PEGR", "PEGY", "PENN", "PEP", "PEPG", "PERI", "PESI", "PET", "PETQ", "PETS", "PETWW", "PETZ",
             "PEV",
             "PFBC", "PFC", "PFG", "PFIE", "PFIS", "PFMT", "PFTAU", "PFTAW", "PFX", "PFXNZ", "PGC", "PGEN", "PGNY",
             "PGY",
             "PGYWW", "PHAR", "PHAT", "PHIO", "PHUN", "PHVS", "PI", "PIII", "PIK", "PINC", "PIRS", "PIXY", "PKBK",
             "PKOH",
             "PLAB", "PLAO", "PLAY", "PLBC", "PLBY", "PLCE", "PLL", "PLMI", "PLMIW", "PLMJ", "PLMJU", "PLMR", "PLPC",
             "PLRX", "PLSE", "PLTK", "PLTN", "PLTNR", "PLTNU", "PLTNW", "PLUG", "PLUR", "PLUS", "PLXS", "PLYA", "PMCB",
             "PMD", "PMEC", "PMN", "PMTS", "PMVP", "PNBK", "PNFP", "PNFPP", "PNRG", "PNTG", "POAI", "POCI", "PODC",
             "PODD",
             "POET", "POLA", "POOL", "POWI", "POWL", "POWW", "POWWP", "PPBI", "PPBT", "PPC", "PPIH", "PPSI", "PPTA",
             "PPYA", "PPYAU", "PPYAW", "PRAA", "PRAX", "PRCH", "PRCT", "PRDO", "PRE", "PRENW", "PRFT", "PRFX", "PRGS",
             "PRLD", "PRLH", "PRME", "PROC", "PROCW", "PROF", "PROK", "PROP", "PROV", "PRPH", "PRPL", "PRPO", "PRQR",
             "PRSO", "PRST", "PRSTW", "PRTA", "PRTC", "PRTG", "PRTH", "PRTS", "PRVA", "PRZO", "PSEC", "PSHG", "PSMT",
             "PSNL", "PSNY", "PSNYW", "PSTV", "PSTX", "PT", "PTC", "PTCT", "PTEN", "PTGX", "PTIX", "PTLO", "PTMN",
             "PTON",
             "PTPI", "PTSI", "PTVE", "PTWO", "PTWOU", "PTWOW", "PUBM", "PUCKW", "PULM", "PVBC", "PWFL", "PWM", "PWOD",
             "PWP", "PWUP", "PWUPW", "PXDT", "PXLW", "PXS", "PXSAP", "PXSAW", "PYCR", "PYPD", "PYPL", "PYXS", "PZZA",
             "QCOM", "QCRH", "QDEL", "QDRO", "QDROW", "QETA", "QETAR", "QFIN", "QH", "QIPT", "QLGN", "QLI", "QLYS",
             "QMCO",
             "QNCX", "QNRX", "QNST", "QOMO", "QQQX", "QRHC", "QRTEA", "QRTEB", "QRTEP", "QRVO", "QSG", "QSI", "QSIAW",
             "QTI", "QTRX", "QTTB", "QUBT", "QUIK", "QURE", "RAIL", "RAND", "RANI", "RAPT", "RARE", "RAVE", "RAY",
             "RAYA",
             "RBB", "RBBN", "RBCAA", "RBKB", "RCAT", "RCEL", "RCKT", "RCKY", "RCM", "RCMT", "RCON", "RCRT", "RDCM",
             "RDFN",
             "RDHL", "RDI", "RDIB", "RDNT", "RDUS", "RDVT", "RDWR", "RDZN", "REAL", "REAX", "REBN", "REE", "REFI",
             "REFR",
             "REG", "REGCO", "REGCP", "REGN", "REKR", "RELI", "RELIW", "RELL", "RELY", "RENB", "RENE", "RENEU", "RENEW",
             "RENT", "REPL", "RETO", "REVB", "REVBW", "REYN", "RFAC", "RFACR", "RFACW", "RFIL", "RGC", "RGCO", "RGEN",
             "RGF", "RGLD", "RGLS", "RGNX", "RGP", "RGS", "RGTI", "RGTIW", "RICK", "RIGL", "RILY", "RILYG", "RILYK",
             "RILYL", "RILYM", "RILYN", "RILYO", "RILYP", "RILYT", "RILYZ", "RIOT", "RIVN", "RKDA", "RKLB", "RLAY",
             "RLMD",
             "RLYB", "RMBI", "RMBL", "RMBS", "RMCF", "RMCO", "RMNI", "RMR", "RMTI", "RNA", "RNAC", "RNAZ", "RNLX",
             "RNW",
             "RNWWW", "RNXT", "ROAD", "ROCK", "ROCL", "ROCLW", "ROIC", "ROIV", "ROKU", "ROMA", "ROOT", "ROP", "ROST",
             "RPAY", "RPD", "RPHM", "RPID", "RPRX", "RPTX", "RR", "RRBI", "RRGB", "RRR", "RSLS", "RSSS", "RSVR", "RTC",
             "RUM", "RUMBW", "RUN", "RUSHA", "RUSHB", "RVMD", "RVMDW", "RVNC", "RVPH", "RVPHW", "RVSB", "RVSN", "RVSNW",
             "RVYL", "RWAY", "RWAYL", "RWAYZ", "RWOD", "RWODR", "RWODU", "RWODW", "RXRX", "RXST", "RXT", "RYAAY",
             "RYTM",
             "RZLT", "SABR", "SABS", "SABSW", "SAFT", "SAGE", "SAI", "SAIA", "SAIC", "SAITW", "SAMG", "SANA", "SANG",
             "SANM", "SANW", "SASR", "SATL", "SATS", "SAVA", "SBAC", "SBCF", "SBET", "SBFG", "SBFM", "SBFMW", "SBGI",
             "SBLK", "SBRA", "SBSI", "SBT", "SBUX", "SCHL", "SCKT", "SCLX", "SCLXW", "SCNI", "SCOR", "SCPH", "SCSC",
             "SCVL", "SCWO", "SCWX", "SCYX", "SDA", "SDAWW", "SDGR", "SDIG", "SDOT", "SEAT", "SEDG", "SEED", "SEEL",
             "SEER", "SEIC", "SELF", "SELX", "SENEA", "SENEB", "SEPA", "SEPAU", "SEPAW", "SERA", "SERV", "SEVN", "SEZL",
             "SFBC", "SFIX", "SFM", "SFNC", "SFST", "SFWL", "SGA", "SGBX", "SGC", "SGD", "SGH", "SGHT", "SGLY", "SGMA",
             "SGML", "SGMO", "SGMT", "SGRP", "SGRY", "SHBI", "SHC", "SHCR", "SHCRW", "SHEN", "SHFS", "SHFSW", "SHIM",
             "SHIP", "SHLS", "SHLT", "SHMD", "SHMDW", "SHOO", "SHOT", "SHOTW", "SHPH", "SHPW", "SHPWW", "SHYF", "SIBN",
             "SIDU", "SIEB", "SIFY", "SIGA", "SIGI", "SIGIP", "SILC", "SILK", "SILO", "SIMO", "SINT", "SIRI", "SISI",
             "SITM", "SJ", "SKGR", "SKGRW", "SKIN", "SKWD", "SKYE", "SKYT", "SKYW", "SKYX", "SLAB", "SLAM", "SLAMU",
             "SLAMW", "SLDB", "SLDP", "SLDPW", "SLE", "SLGL", "SLM", "SLMBP", "SLN", "SLNA", "SLNAW", "SLNG", "SLNH",
             "SLNHP", "SLNO", "SLP", "SLRC", "SLRN", "SLRX", "SLS", "SLVO", "SMBC", "SMCI", "SMFL", "SMID", "SMLR",
             "SMMT",
             "SMPL", "SMSI", "SMTC", "SMTI", "SMX", "SMXT", "SMXWW", "SNAL", "SNAX", "SNAXW", "SNBR", "SNCR", "SNCRL",
             "SNCY", "SND", "SNDL", "SNDX", "SNES", "SNEX", "SNFCA", "SNGX", "SNOA", "SNPO", "SNPS", "SNPX", "SNSE",
             "SNT",
             "SNTG", "SNTI", "SNY", "SOBR", "SOFI", "SOGP", "SOHO", "SOHOB", "SOHON", "SOHOO", "SOHU", "SOND", "SONDW",
             "SONM", "SONN", "SONO", "SOPA", "SOPH", "SOTK", "SOUN", "SOUNW", "SOWG", "SP", "SPCB", "SPEC", "SPECW",
             "SPFI", "SPGC", "SPI", "SPKL", "SPNS", "SPOK", "SPPL", "SPRB", "SPRC", "SPRO", "SPRY", "SPSC", "SPT",
             "SPTN",
             "SPWH", "SPWR", "SQFT", "SQFTP", "SQFTW", "SRAD", "SRBK", "SRCE", "SRCL", "SRDX", "SRM", "SRPT", "SRRK",
             "SRTS", "SRZN", "SRZNW", "SSBI", "SSBK", "SSIC", "SSKN", "SSNC", "SSNT", "SSP", "SSRM", "SSSS", "SSSSL",
             "SSTI", "SSYS", "STAA", "STAF", "STBA", "STBX", "STCN", "STEP", "STER", "STGW", "STHO", "STI", "STIM",
             "STKH",
             "STKL", "STKS", "STLD", "STNE", "STOK", "STRA", "STRL", "STRM", "STRO", "STRR", "STRRP", "STRS", "STRT",
             "STSS", "STSSW", "STTK", "STX", "SUGP", "SUPN", "SURG", "SURGW", "SUUN", "SVC", "SVCO", "SVII", "SVIIU",
             "SVIIW", "SVMH", "SVMHW", "SVRA", "SVRE", "SVREW", "SWAG", "SWAV", "SWBI", "SWIM", "SWIN", "SWKH", "SWKHL",
             "SWKS", "SWSS", "SWTX", "SWVL", "SWVLW", "SXTC", "SXTP", "SXTPW", "SY", "SYBT", "SYBX", "SYM", "SYNA",
             "SYPR",
             "SYRA", "SYRE", "SYRS", "SYT", "SYTA", "SYTAW", "TACT", "TAIT", "TALK", "TALKW", "TANH", "TAOP", "TARA",
             "TARS", "TASK", "TAST", "TATT", "TAYD", "TBBK", "TBIO", "TBLA", "TBLAW", "TBLD", "TBLT", "TBMC", "TBMCR",
             "TBNK", "TBPH", "TBRG", "TC", "TCBC", "TCBI", "TCBIO", "TCBK", "TCBP", "TCBPW", "TCBS", "TCBX", "TCJH",
             "TCMD", "TCOM", "TCON", "TCPC", "TCRT", "TCRX", "TCTM", "TCX", "TDUP", "TEAM", "TECH", "TECTP", "TELA",
             "TELO", "TENB", "TENK", "TENKR", "TENKU", "TENX", "TER", "TERN", "TETE", "TFFP", "TFIN", "TFINP", "TFSL",
             "TGAA", "TGAN", "TGL", "TGTX", "TH", "THAR", "THCH", "THCP", "THCPW", "THFF", "THMO", "THRD", "THRM",
             "THRY",
             "THTX", "TIGO", "TIGR", "TIL", "TILE", "TIPT", "TIRX", "TITN", "TIVC", "TKLF", "TKNO", "TLF", "TLGY",
             "TLGYW",
             "TLIS", "TLPH", "TLRY", "TLS", "TLSA", "TLSI", "TLSIW", "TMC", "TMCI", "TMCWW", "TMDX", "TMTC", "TMTCR",
             "TMTCU", "TMUS", "TNDM", "TNGX", "TNON", "TNONW", "TNXP", "TNYA", "TOI", "TOMZ", "TOP", "TORO", "TOUR",
             "TOWN", "TPCS", "TPG", "TPGXL", "TPIC", "TPST", "TRAW", "TRDA", "TREE", "TRIB", "TRIN", "TRINL", "TRINZ",
             "TRIP", "TRMB", "TRMD", "TRMK", "TRML", "TRNR", "TRNS", "TRON", "TRONW", "TROO", "TROW", "TRS", "TRSG",
             "TRST", "TRUE", "TRUG", "TRUP", "TRVG", "TRVI", "TRVN", "TSAT", "TSBK", "TSBX", "TSCO", "TSEM", "TSHA",
             "TSLA", "TSRI", "TSVT", "TTD", "TTEC", "TTEK", "TTGT", "TTMI", "TTNP", "TTOO", "TTSH", "TTWO", "TURB",
             "TURN",
             "TUSK", "TVGN", "TVGNW", "TVTX", "TW", "TWG", "TWIN", "TWKS", "TWLV", "TWOU", "TWST", "TXG", "TXMD", "TXN",
             "TXRH", "TYGO", "TYRA", "TZOO", "UAL", "UBCP", "UBFO", "UBSI", "UBX", "UBXG", "UCAR", "UCBI", "UCBIO",
             "UCL",
             "UCTT", "UDMY", "UEIC", "UFCS", "UFPI", "UFPT", "UG", "UGRO", "UHG", "UHGWW", "UK", "UKOMW", "ULBI",
             "ULCC",
             "ULH", "ULTA", "ULY", "UMBF", "UNB", "UNCY", "UNIT", "UNTY", "UONE", "UONEK", "UPBD", "UPC", "UPLD",
             "UPST",
             "UPWK", "UPXI", "URBN", "URGN", "UROY", "USAP", "USAU", "USCB", "USEA", "USEG", "USGO", "USGOW", "USIO",
             "USLM", "USOI", "UTHR", "UTMD", "UTSI", "UVSP", "UXIN", "VABK", "VALN", "VALU", "VANI", "VBFC", "VBIV",
             "VBNK", "VBTX", "VC", "VCEL", "VCIG", "VCNX", "VCSA", "VCTR", "VCYT", "VECO", "VEEE", "VEON", "VERA",
             "VERB",
             "VERI", "VERO", "VERU", "VERV", "VERX", "VERY", "VEV", "VFF", "VFS", "VFSWW", "VGAS", "VGASW", "VIA",
             "VIASP",
             "VIAV", "VICR", "VIGL", "VINC", "VINO", "VINP", "VIOT", "VIR", "VIRC", "VIRI", "VIRT", "VIRX", "VISL",
             "VITL",
             "VIVK", "VKTX", "VLCN", "VLGEA", "VLY", "VLYPO", "VLYPP", "VMAR", "VMCA", "VMD", "VMEO", "VNDA", "VNET",
             "VNOM", "VOD", "VOR", "VOXR", "VOXX", "VRA", "VRAR", "VRAX", "VRCA", "VRDN", "VREX", "VRM", "VRME",
             "VRMEW",
             "VRNA", "VRNS", "VRNT", "VRPX", "VRRM", "VRSK", "VRSN", "VRTX", "VS", "VSAC", "VSAT", "VSEC", "VSME",
             "VSSYW",
             "VSTA", "VSTE", "VSTEW", "VSTM", "VTGN", "VTNR", "VTRS", "VTRU", "VTSI", "VTVT", "VTYX", "VUZI", "VVOS",
             "VVPR", "VWE", "VWEWW", "VXRT", "VYGR", "VYNE", "WABC", "WAFD", "WAFDP", "WAFU", "WALD", "WALDW", "WASH",
             "WATT", "WAVD", "WAVE", "WAVS", "WB", "WBA", "WBD", "WBUY", "WDAY", "WDC", "WDFC", "WEN", "WERN", "WEST",
             "WESTW", "WETH", "WEYS", "WFCF", "WFRD", "WGS", "WGSWW", "WHF", "WHFCL", "WHLM", "WHLR", "WHLRD", "WHLRP",
             "WILC", "WIMI", "WINA", "WING", "WINT", "WINV", "WINVR", "WINVW", "WIRE", "WISA", "WIX", "WKEY", "WKHS",
             "WKME", "WKSP", "WKSPW", "WLDN", "WLDS", "WLDSW", "WLFC", "WLGS", "WMG", "WMPN", "WNEB", "WNW", "WOOF",
             "WORX", "WPRT", "WRAP", "WRLD", "WRNT", "WSBC", "WSBCP", "WSBF", "WSC", "WSFS", "WTBA", "WTFC", "WTFCM",
             "WTFCP", "WTMA", "WTMAR", "WTO", "WTW", "WULF", "WVE", "WVVI", "WVVIP", "WW", "WWD", "WYNN", "XAIR",
             "XBIO",
             "XBIOW", "XBIT", "XBP", "XBPEW", "XCUR", "XEL", "XELA", "XELAP", "XELB", "XENE", "XERS", "XFIN", "XFINW",
             "XFOR", "XGN", "XLO", "XMTR", "XNCR", "XNET", "XOMA", "XOMAO", "XOMAP", "XOS", "XOSWW", "XP", "XPEL",
             "XPON",
             "XRAY", "XRTX", "XRX", "XTIA", "XTKG", "XTLB", "XWEL", "XXII", "XYLO", "YGMZ", "YHGJ", "YI", "YIBO", "YJ",
             "YMAB", "YORW", "YOSH", "YOTA", "YOTAU", "YOTAW", "YQ", "YS", "YSBPW", "YTEN", "YTRA", "YY", "YYAI",
             "YYGH",
             "Z", "ZAPP", "ZAPPW", "ZBAO", "ZBRA", "ZCAR", "ZCMD", "ZD", "ZENV", "ZEO", "ZEOWW", "ZEUS", "ZG", "ZI",
             "ZIMV", "ZION", "ZIONL", "ZIONO", "ZIONP", "ZJYL", "ZKIN", "ZLAB", "ZLS", "ZM", "ZNTL", "ZOOZ", "ZOOZW",
             "ZPTA", "ZPTAW", "ZS", "ZTEK", "ZUMZ", "ZURA", "ZURAW", "ZVRA", "ZVSA", "ZYME", "ZYXI", "A", "AA", "AACT",
             "AAN", "AAP", "AAT", "AB", "ABBV", "ABEV", "ABG", "ABM", "ABR", "ABR^D", "ABR^E", "ABR^F",
             "ABT", "AC", "ACA", "ACCO", "ACEL", "ACHR", "ACI", "ACM", "ACN", "ACP", "ACP^A", "ACR", "ACR^C", "ACR^D",
             "ACRE", "ACV", "ADC", "ADC^A", "ADCT", "ADM", "ADNT", "ADT", "ADX", "AEE", "AEFC", "AEG", "AEM", "AEO",
             "AER",
             "AES", "AESI", "AEVA", "AFB", "AFG", "AFGB", "AFGC", "AFGD", "AFGE", "AFL", "AFT", "AG", "AGCO", "AGD",
             "AGI",
             "AGL", "AGM", "AGM^C", "AGM^D", "AGM^E", "AGM^F", "AGM^G", "AGO", "AGR", "AGRO", "AGS", "AGX", "AHH",
             "AHH^A",
             "AHL^C", "AHL^D", "AHL^E", "AHR", "AHT", "AHT^D", "AHT^F", "AHT^G", "AHT^H", "AHT^I", "AI", "AIF", "AIG",
             "AIN",
             "AIO", "AIR", "AIRC", "AIT", "AIU", "AIV", "AIZ", "AIZN", "AJG", "AJX", "AKA", "AKO/A", "AKO/B", "AKR",
             "AL",
             "AL^A", "ALB", "ALB^A", "ALC", "ALE", "ALEX", "ALG", "ALIT", "ALK", "ALL", "ALL^B", "ALL^H", "ALL^I",
             "ALL^J",
             "ALLE", "ALLG", "ALLY", "ALSN", "ALTG", "ALTG^A", "ALTM", "ALUR", "ALV", "ALX", "AM", "AMBC", "AMBP",
             "AMC",
             "AMCR", "AME", "AMG", "AMH", "AMH^G", "AMH^H", "AMK", "AMN", "AMP", "AMPS", "AMPX", "AMPY", "AMR", "AMRC",
             "AMT", "AMTB", "AMTD", "AMWL", "AMX", "AN", "ANET", "ANF", "ANG^A", "ANG^B", "ANRO", "ANVS", "AOD", "AOMR",
             "AON", "AORT", "AOS", "AP", "APAM", "APCA", "APD", "APG", "APH", "APLE", "APO", "APO^A", "APOS", "APTV",
             "AQN",
             "AQNB", "AQNU", "AR", "ARC", "ARCH", "ARCO", "ARDC", "ARE", "ARES", "ARGD", "ARGO^A", "ARI", "ARIS", "ARL",
             "ARLO", "ARMK", "AROC", "ARR", "ARR^C", "ARW", "AS", "ASA", "ASAI", "ASAN", "ASB", "ASB^E", "ASB^F",
             "ASBA",
             "ASC", "ASG", "ASGI", "ASGN", "ASH", "ASIX", "ASPN", "ASR", "ASX", "ATCO^D", "ATCO^H", "ATEN", "ATGE",
             "ATH^A",
             "ATH^B", "ATH^C", "ATH^D", "ATH^E", "ATHM", "ATHS", "ATI", "ATIP", "ATKR", "ATMU", "ATO", "ATR", "ATS",
             "ATUS",
             "AU", "AUB", "AUB^A", "AUNA", "AVA", "AVAL", "AVB", "AVD", "AVK", "AVNS", "AVNT", "AVTR", "AVY", "AWF",
             "AWI",
             "AWK", "AWP", "AWR", "AX", "AXL", "AXP", "AXR", "AXS", "AXS^E", "AXTA", "AYI", "AZEK", "AZO", "AZUL",
             "AZZ",
             "B", "BA", "BABA", "BAC", "BAC^B", "BAC^E", "BAC^K", "BAC^L", "BAC^M", "BAC^N", "BAC^O", "BAC^P", "BAC^Q",
             "BAC^S", "BAH", "BAK", "BALL", "BALY", "BAM", "BANC", "BANC^F", "BAP", "BARK", "BAX", "BB", "BBAI", "BBAR",
             "BBD", "BBDC", "BBDO", "BBN", "BBU", "BBUC", "BBVA", "BBW", "BBWI", "BBY", "BC", "BC^A", "BC^B", "BC^C",
             "BCAT",
             "BCC", "BCE", "BCH", "BCO", "BCS", "BCSF", "BCX", "BDC", "BDJ", "BDN", "BDX", "BE", "BEDU", "BEKE", "BEN",
             "BEP", "BEP^A", "BEPC", "BEPH", "BEPI", "BEPJ", "BERY", "BEST", "BF/A", "BF/B", "BFAC", "BFAM", "BFH",
             "BFK",
             "BFLY", "BFS", "BFS^D", "BFS^E", "BFZ", "BG", "BGB", "BGH", "BGR", "BGS", "BGSF", "BGT", "BGX", "BGY",
             "BH",
             "BHC", "BHE", "BHIL", "BHK", "BHLB", "BHP", "BHR", "BHR^B", "BHR^D", "BHV", "BHVN", "BIG", "BIGZ", "BILL",
             "BIO", "BIO/B", "BIP", "BIP^A", "BIP^B", "BIPC", "BIPH", "BIPI", "BIRK", "BIT", "BJ", "BK", "BKD", "BKDT",
             "BKE", "BKH", "BKKT", "BKN", "BKSY", "BKT", "BKU", "BLCO", "BLD", "BLDR", "BLE", "BLK", "BLND", "BLW",
             "BLX",
             "BMA", "BME", "BMEZ", "BMI", "BML^G", "BML^H", "BML^J", "BML^L", "BMN", "BMO", "BMY", "BN", "BNED", "BNH",
             "BNJ", "BNL", "BNRE", "BNS", "BNY", "BOC", "BODI", "BOE", "BOH", "BOH^A", "BOOT", "BORR", "BOWL", "BOX",
             "BP",
             "BPT", "BR", "BRBR", "BRC", "BRCC", "BRDG", "BRFS", "BRK/A", "BRK/B", "BRO", "BROS", "BRSP", "BRT", "BRW",
             "BRX", "BSAC", "BSBR", "BSIG", "BSL", "BSM", "BST", "BSTZ", "BSX", "BTA", "BTCM", "BTE", "BTI", "BTO",
             "BTT",
             "BTU", "BTZ", "BUD", "BUI", "BUR", "BURL", "BV", "BVN", "BW", "BW^A", "BWA", "BWG", "BWLP", "BWNB", "BWSN",
             "BWXT", "BX", "BXC", "BXMT", "BXMX", "BXP", "BXSL", "BY", "BYD", "BYM", "BYON", "BZH", "C", "C^N", "CAAP",
             "CABO", "CACI", "CADE", "CADE^A", "CAE", "CAF", "CAG", "CAH", "CAL", "CALX", "CANG", "CAPL", "CARR",
             "CARS",
             "CAT", "CATO", "CAVA", "CB", "CBH", "CBL", "CBRE", "CBT", "CBU", "CBZ", "CC", "CCI", "CCIA", "CCIF", "CCJ",
             "CCK", "CCL", "CCM", "CCO", "CCRD", "CCS", "CCU", "CCZ", "CDE", "CDLR", "CDP", "CDR^B", "CDR^C", "CDRE",
             "CE",
             "CEE", "CEIX", "CEM", "CEPU", "CF", "CFG", "CFG^D", "CFG^E", "CFR", "CFR^B", "CGA", "CGAU", "CHCT", "CHD",
             "CHE", "CHGG", "CHH", "CHMI", "CHMI^A", "CHMI^B", "CHN", "CHPT", "CHT", "CHWY", "CI", "CIA", "CIB", "CIEN",
             "CIF", "CIG", "CII", "CIM", "CIM^A", "CIM^B", "CIM^C", "CIM^D", "CINT", "CIO", "CIO^A", "CION", "CIVI",
             "CL",
             "CLB", "CLBR", "CLCO", "CLDT", "CLDT^A", "CLF", "CLH", "CLPR", "CLS", "CLVT", "CLVT^A", "CLW", "CLX", "CM",
             "CMA", "CMC", "CMCM", "CMG", "CMI", "CMP", "CMRE", "CMRE^B", "CMRE^C", "CMRE^D", "CMRE^E", "CMS", "CMS^B",
             "CMS^C", "CMSA", "CMSC", "CMSD", "CMTG", "CMU", "CNA", "CNC", "CNDA", "CNF", "CNHI", "CNI", "CNK", "CNM",
             "CNMD", "CNNE", "CNO", "CNO^A", "CNP", "CNQ", "CNS", "CNX", "CODI", "CODI^A", "CODI^B", "CODI^C", "COF",
             "COF^I", "COF^J", "COF^K", "COF^L", "COF^N", "COHR", "COLD", "COMP", "COOK", "COP", "COR", "COTY", "COUR",
             "CP",
             "CPA", "CPAC", "CPAY", "CPB", "CPF", "CPK", "CPNG", "CPRI", "CPS", "CPT", "CQP", "CR", "CRBG", "CRC",
             "CRD/A",
             "CRD/B", "CRGY", "CRH", "CRI", "CRK", "CRL", "CRM", "CRS", "CRT", "CSAN", "CSL", "CSR", "CSR^C", "CSTM",
             "CSV",
             "CTA^A", "CTA^B", "CTBB", "CTDD", "CTLT", "CTO", "CTO^A", "CTOS", "CTR", "CTRA", "CTRE", "CTRI", "CTS",
             "CTV",
             "CTVA", "CUBB", "CUBE", "CUBI", "CUBI^E", "CUBI^F", "CUK", "CULP", "CURV", "CUZ", "CVE", "CVEO", "CVI",
             "CVNA",
             "CVS", "CVX", "CW", "CWAN", "CWEN", "CWH", "CWK", "CWT", "CX", "CXE", "CXH", "CXM", "CXT", "CXW", "CYD",
             "CYH",
             "CZOO", "D", "DAC", "DAL", "DAN", "DAO", "DAR", "DAVA", "DAY", "DB", "DBD", "DBI", "DBL", "DBRG", "DBRG^H",
             "DBRG^I", "DBRG^J", "DCF", "DCI", "DCO", "DD", "DDD", "DDL", "DDS", "DDT", "DE", "DEA", "DEC", "DECK",
             "DEI",
             "DELL", "DEO", "DESP", "DFH", "DFIN", "DFP", "DFS", "DG", "DGX", "DHF", "DHI", "DHR", "DHT", "DHX", "DIAX",
             "DIN", "DINO", "DIS", "DK", "DKL", "DKS", "DLB", "DLNG", "DLNG^A", "DLNG^B", "DLR", "DLR^J", "DLR^K",
             "DLR^L",
             "DLX", "DLY", "DM", "DMA", "DMB", "DMO", "DNA", "DNB", "DNMR", "DNOW", "DNP", "DO", "DOC", "DOCN", "DOCS",
             "DOLE", "DOMA", "DOUG", "DOV", "DOW", "DPG", "DPZ", "DQ", "DRD", "DRH", "DRH^A", "DRI", "DRQ", "DSL",
             "DSM",
             "DSU", "DSX", "DSX^B", "DT", "DTB", "DTC", "DTE", "DTF", "DTG", "DTM", "DTW", "DUK", "DUK^A", "DUKB", "DV",
             "DVA", "DVN", "DX", "DX^C", "DXC", "DXYZ", "DY", "E", "EAF", "EAI", "EARN", "EAT", "EB", "EBF", "EBR",
             "EBS",
             "EC", "ECAT", "ECC", "ECC^D", "ECCC", "ECCF", "ECCV", "ECCW", "ECCX", "ECL", "ECO", "ECVT", "ED", "EDD",
             "EDF",
             "EDN", "EDR", "EDU", "EE", "EEA", "EEX", "EFC", "EFC^A", "EFC^B", "EFC^C", "EFC^D", "EFC^E", "EFR", "EFT",
             "EFX", "EFXT", "EG", "EGF", "EGO", "EGP", "EGY", "EHAB", "EHC", "EHI", "EIC", "EICA", "EICB", "EICC",
             "EIG",
             "EIX", "EL", "ELAN", "ELC", "ELF", "ELME", "ELP", "ELPC", "ELS", "ELV", "EMD", "EME", "EMF", "EMN", "EMO",
             "EMP", "EMR", "ENB", "ENFN", "ENIC", "ENLC", "ENO", "ENOV", "ENR", "ENS", "ENV", "ENVA", "ENZ", "EOD",
             "EOG",
             "EOI", "EOS", "EOT", "EP^C", "EPAC", "EPAM", "EPC", "EPD", "EPR", "EPR^C", "EPR^E", "EPR^G", "EPRT",
             "EQBK",
             "EQC", "EQC^D", "EQH", "EQH^A", "EQH^C", "EQNR", "EQR", "EQS", "EQT", "ERF", "ERJ", "ERO", "ES", "ESAB",
             "ESE",
             "ESI", "ESNT", "ESRT", "ESS", "ESTC", "ET", "ET^I", "ETB", "ETD", "ETG", "ETI^", "ETJ", "ETN", "ETO",
             "ETR",
             "ETRN", "ETV", "ETW", "ETWO", "ETX", "ETY", "EURN", "EVA", "EVC", "EVEX", "EVF", "EVG", "EVH", "EVN",
             "EVR",
             "EVRI", "EVT", "EVTC", "EVTL", "EW", "EXG", "EXK", "EXP", "EXPD", "EXR", "EXTO", "F", "F^B", "F^C", "F^D",
             "FAF", "FAM", "FATH", "FBIN", "FBK", "FBP", "FBRT", "FBRT^E", "FC", "FCF", "FCN", "FCPT", "FCRX", "FCT",
             "FCX",
             "FDP", "FDX", "FE", "FEDU", "FENG", "FERG", "FET", "FF", "FFA", "FFC", "FFWM", "FG", "FGB", "FGN", "FHI",
             "FHN",
             "FHN^B", "FHN^C", "FHN^E", "FHN^F", "FI", "FICO", "FIGS", "FIHL", "FINS", "FINV", "FIS", "FIX", "FL",
             "FLC",
             "FLNG", "FLO", "FLR", "FLS", "FLUT", "FMC", "FMN", "FMS", "FMX", "FMY", "FN", "FNA", "FNB", "FND", "FNF",
             "FNV",
             "FOA", "FOF", "FOR", "FOUR", "FPF", "FPH", "FPI", "FR", "FRA", "FREY", "FRGE", "FRO", "FRT", "FRT^C",
             "FSCO",
             "FSD", "FSK", "FSLY", "FSM", "FSS", "FT", "FTHY", "FTI", "FTK", "FTS", "FTV", "FUBO", "FUL", "FUN", "FVRR",
             "G",
             "GAB", "GAB^G", "GAB^H", "GAB^K", "GAM", "GAM^B", "GATO", "GATX", "GB", "GBAB", "GBCI", "GBLI", "GBTG",
             "GBX",
             "GCI", "GCO", "GCTS", "GCV", "GD", "GDDY", "GDL", "GDO", "GDOT", "GDV", "GDV^H", "GDV^K", "GE", "GEF",
             "GEL",
             "GENI", "GEO", "GES", "GETR", "GETY", "GEV", "GF", "GFF", "GFI", "GFL", "GFR", "GGB", "GGG", "GGT",
             "GGT^G",
             "GGZ", "GHC", "GHG", "GHI", "GHLD", "GHM", "GHY", "GIB", "GIC", "GIL", "GIS", "GJH", "GJO", "GJP", "GJR",
             "GJS",
             "GJT", "GKOS", "GL", "GL^D", "GLOB", "GLOG^A", "GLOP^A", "GLOP^B", "GLOP^C", "GLP", "GLP^B", "GLT", "GLW",
             "GM",
             "GME", "GMED", "GMRE", "GMRE^A", "GMS", "GNE", "GNK", "GNL", "GNL^A", "GNL^B", "GNL^D", "GNL^E", "GNRC",
             "GNT",
             "GNT^A", "GNTY", "GNW", "GOF", "GOLD", "GOLF", "GOOS", "GOTU", "GPC", "GPI", "GPJA", "GPK", "GPMT",
             "GPMT^A",
             "GPN", "GPOR", "GPRK", "GPS", "GRBK", "GRBK^A", "GRC", "GRMN", "GRND", "GRNT", "GROV", "GRX", "GS", "GS^A",
             "GS^C", "GS^D", "GS^K", "GSBD", "GSK", "GSL", "GSL^B", "GTES", "GTLS", "GTLS^B", "GTN", "GTY", "GUG",
             "GUT",
             "GUT^C", "GVA", "GWH", "GWRE", "GWW", "GXO", "H", "HAE", "HAFN", "HAL", "HASI", "HAYW", "HBB", "HBI",
             "HBM",
             "HCA", "HCC", "HCI", "HCXY", "HD", "HDB", "HE", "HEI", "HEI/A", "HEQ", "HES", "HESM", "HFRO", "HFRO^A",
             "HG",
             "HGLB", "HGTY", "HGV", "HHH", "HI", "HIE", "HIG", "HIG^G", "HII", "HIMS", "HIO", "HIPO", "HIW", "HIX",
             "HKD",
             "HL", "HL^B", "HLF", "HLI", "HLIO", "HLLY", "HLN", "HLT", "HLX", "HMC", "HMN", "HMY", "HNI", "HOG", "HOMB",
             "HOUS", "HOV", "HP", "HPE", "HPF", "HPI", "HPP", "HPP^C", "HPQ", "HPS", "HQH", "HQL", "HR", "HRB", "HRI",
             "HRL",
             "HRT", "HRTG", "HSBC", "HSHP", "HSY", "HTD", "HTFB", "HTFC", "HTGC", "HTH", "HUBB", "HUBS", "HUM", "HUN",
             "HUYA", "HVT", "HVT/A", "HWM", "HXL", "HY", "HYAC", "HYB", "HYI", "HYLN", "HYT", "HZO", "IAE", "IAG",
             "IBM",
             "IBN", "IBP", "IBTA", "ICD", "ICE", "ICL", "ICR^A", "IDA", "IDE", "IDT", "IEX", "IFF", "IFN", "IFS", "IGA",
             "IGD", "IGI", "IGR", "IGT", "IH", "IHD", "IHG", "IHS", "IHTA", "IIF", "IIIN", "IIM", "IIPR", "IIPR^A",
             "IMAX",
             "INFA", "INFY", "ING", "INGR", "INN", "INN^E", "INN^F", "INSI", "INSP", "INST", "INSW", "INVH", "IONQ",
             "IOT",
             "IP", "IPG", "IPI", "IQI", "IQV", "IR", "IRM", "IRS", "IRT", "ISD", "IT", "ITGR", "ITT", "ITUB", "ITW",
             "IVR",
             "IVR^B", "IVR^C", "IVT", "IVZ", "IX", "J", "JBGS", "JBI", "JBK", "JBL", "JBT", "JCE", "JCI", "JEF", "JELD",
             "JEQ", "JFR", "JGH", "JHG", "JHI", "JHS", "JHX", "JILL", "JKS", "JLL", "JLS", "JMIA", "JMM", "JNJ", "JNPR",
             "JOBY", "JOE", "JOF", "JPC", "JPI", "JPM", "JPM^C", "JPM^D", "JPM^J", "JPM^K", "JPM^L", "JPM^M", "JQC",
             "JRI",
             "JRS", "JWN", "JXN", "JXN^A", "K", "KAI", "KAR", "KB", "KBH", "KBR", "KCGI", "KD", "KEN", "KEP", "KEX",
             "KEY",
             "KEY^I", "KEY^J", "KEY^K", "KEY^L", "KEYS", "KF", "KFS", "KFY", "KGC", "KGS", "KIM", "KIM^L", "KIM^M",
             "KIM^N",
             "KIND", "KIO", "KKR", "KKRS", "KLG", "KMB", "KMI", "KMPB", "KMPR", "KMT", "KMX", "KN", "KNF", "KNOP",
             "KNSL",
             "KNTK", "KNX", "KO", "KODK", "KOF", "KOP", "KORE", "KOS", "KR", "KRC", "KREF", "KREF^A", "KRG", "KRO",
             "KRP",
             "KSM", "KSS", "KT", "KTB", "KTF", "KTH", "KTN", "KUKE", "KVUE", "KVYO", "KW", "KWR", "KYN", "L", "LAAC",
             "LAC",
             "LAD", "LADR", "LANV", "LAW", "LAZ", "LBRT", "LC", "LCII", "LCW", "LDI", "LDOS", "LDP", "LEA", "LEG",
             "LEN",
             "LEO", "LEV", "LEVI", "LFT", "LFT^A", "LGI", "LH", "LHX", "LICY", "LII", "LITB", "LL", "LLAP", "LLY",
             "LMND",
             "LMT", "LNC", "LNC^D", "LND", "LNG", "LNN", "LOAR", "LOB", "LOCL", "LOMA", "LOW", "LPG", "LPL", "LPX",
             "LRN",
             "LSPD", "LTC", "LTH", "LU", "LUMN", "LUV", "LVS", "LVWR", "LW", "LXP", "LXP^C", "LXU", "LYB", "LYG", "LYV",
             "LZB", "LZM", "M", "MA", "MAA", "MAA^I", "MAC", "MAIN", "MAN", "MANU", "MAS", "MATV", "MATX", "MAV", "MAX",
             "MBC", "MBI", "MC", "MCB", "MCD", "MCI", "MCK", "MCN", "MCO", "MCR", "MCS", "MCW", "MCY", "MD", "MDT",
             "MDU",
             "MDV", "MDV^A", "MEC", "MED", "MEG", "MEGI", "MEI", "MER^K", "MET", "MET^A", "MET^E", "MET^F", "MFA",
             "MFA^B",
             "MFA^C", "MFAN", "MFAO", "MFC", "MFD", "MFG", "MFM", "MG", "MGA", "MGF", "MGM", "MGR", "MGRB", "MGRD",
             "MGRE",
             "MGY", "MHD", "MHF", "MHI", "MHK", "MHLA", "MHN", "MHNC", "MHO", "MIN", "MIO", "MIR", "MITN", "MITT",
             "MITT^A",
             "MITT^B", "MITT^C", "MIY", "MKC", "MKFG", "MKL", "ML", "MLI", "MLM", "MLNK", "MLP", "MLR", "MMC", "MMD",
             "MMI",
             "MMM", "MMS", "MMT", "MMU", "MNR", "MNSO", "MNTN", "MO", "MOD", "MODG", "MODN", "MOGU", "MOH", "MOS",
             "MOV",
             "MP", "MPA", "MPC", "MPLN", "MPLX", "MPV", "MPW", "MPX", "MQT", "MQY", "MRC", "MRDB", "MRK", "MRO", "MS",
             "MS^A", "MS^E", "MS^F", "MS^I", "MS^K", "MS^L", "MS^O", "MS^P", "MSA", "MSB", "MSC", "MSCI", "MSD", "MSDL",
             "MSGE", "MSGS", "MSI", "MSM", "MT", "MTAL", "MTB", "MTB^H", "MTD", "MTDR", "MTG", "MTH", "MTN", "MTR",
             "MTRN",
             "MTUS", "MTW", "MTX", "MTZ", "MUA", "MUC", "MUE", "MUFG", "MUI", "MUJ", "MUR", "MUSA", "MUX", "MVF", "MVO",
             "MVT", "MWA", "MX", "MXE", "MXF", "MYD", "MYE", "MYI", "MYN", "MYTE", "NABL", "NAC", "NAD", "NAN", "NAPA",
             "NAT", "NATL", "NAZ", "NBB", "NBHC", "NBR", "NBXG", "NC", "NCA", "NCDL", "NCLH", "NCV", "NCV^A", "NCZ",
             "NCZ^A",
             "NDMO", "NDP", "NE", "NEA", "NEE", "NEE^N", "NEE^R", "NEM", "NEP", "NET", "NEU", "NEUE", "NEXA", "NFG",
             "NFJ",
             "NFYS", "NGG", "NGL", "NGL^B", "NGL^C", "NGS", "NGVC", "NGVT", "NHI", "NI", "NIC", "NIE", "NIM", "NINE",
             "NIO",
             "NJR", "NKE", "NKX", "NL", "NLOP", "NLY", "NLY^F", "NLY^G", "NLY^I", "NMAI", "NMCO", "NMG", "NMI", "NMM",
             "NMR",
             "NMS", "NMT", "NMZ", "NNI", "NNN", "NNY", "NOA", "NOAH", "NOC", "NOG", "NOK", "NOM", "NOMD", "NOTE", "NOV",
             "NOVA", "NOW", "NPCT", "NPFD", "NPK", "NPO", "NPV", "NPWR", "NQP", "NR", "NRDY", "NREF", "NREF^A", "NRG",
             "NRGV", "NRK", "NRP", "NRT", "NRUC", "NS^A", "NS^B", "NS^C", "NSA", "NSA^A", "NSC", "NSP", "NSS", "NTB",
             "NTG",
             "NTR", "NTST", "NTZ", "NU", "NUE", "NUS", "NUV", "NUVB", "NUW", "NVG", "NVGS", "NVO", "NVR", "NVRI",
             "NVRO",
             "NVS", "NVST", "NVT", "NWG", "NWN", "NX", "NXC", "NXDT", "NXDT^A", "NXE", "NXG", "NXJ", "NXN", "NXP",
             "NXRT",
             "NYC", "NYCB", "NYCB^A", "NYCB^U", "NYT", "NZF", "O", "O^", "OAK^A", "OAK^B", "OBDC", "OBDE", "OBK", "OC",
             "OCFT", "OCN", "ODC", "ODV", "OEC", "OFG", "OGE", "OGN", "OGS", "OHI", "OI", "OIA", "OII", "OIS", "OKE",
             "OKLO",
             "OLN", "OLO", "OLP", "OMC", "OMF", "OMI", "ONL", "ONON", "ONTF", "ONTO", "OOMA", "OPAD", "OPFI", "OPP",
             "OPP^A",
             "OPP^B", "OPY", "OR", "ORA", "ORAN", "ORC", "ORCL", "ORI", "ORN", "OSCR", "OSG", "OSI", "OSK", "OTIS",
             "OUST",
             "OUT", "OVV", "OWL", "OWLT", "OXM", "OXY", "PAAS", "PAC", "PACK", "PACS", "PAG", "PAGS", "PAI", "PAM",
             "PAR",
             "PARR", "PATH", "PAXS", "PAY", "PAYC", "PB", "PBA", "PBF", "PBH", "PBI", "PBI^B", "PBR", "PBT", "PCF",
             "PCG",
             "PCK", "PCM", "PCN", "PCOR", "PCQ", "PD", "PDI", "PDM", "PDO", "PDS", "PDT", "PDX", "PEB", "PEB^E",
             "PEB^F",
             "PEB^G", "PEB^H", "PEG", "PEN", "PEO", "PERF", "PFD", "PFE", "PFGC", "PFH", "PFL", "PFLT", "PFN", "PFO",
             "PFS",
             "PFSI", "PG", "PGP", "PGR", "PGRE", "PGRU", "PGZ", "PH", "PHD", "PHG", "PHI", "PHIN", "PHK", "PHM", "PHR",
             "PHT", "PHX", "PHYT", "PII", "PIM", "PINE", "PINS", "PIPR", "PJT", "PK", "PKE", "PKG", "PKST", "PKX", "PL",
             "PLD", "PLNT", "PLOW", "PLTR", "PLYM", "PM", "PMF", "PML", "PMM", "PMO", "PMT", "PMT^A", "PMT^B", "PMT^C",
             "PMTU", "PMX", "PNC", "PNF", "PNI", "PNM", "PNNT", "PNR", "PNST", "PNW", "POR", "POST", "PPG", "PPL",
             "PPT",
             "PR", "PRA", "PRE^J", "PRG", "PRGO", "PRH", "PRI", "PRIF^D", "PRIF^F", "PRIF^G", "PRIF^H", "PRIF^I",
             "PRIF^J",
             "PRIF^K", "PRIF^L", "PRIM", "PRKS", "PRLB", "PRM", "PRMW", "PRO", "PRS", "PRT", "PRU", "PSA", "PSA^F",
             "PSA^G",
             "PSA^H", "PSA^I", "PSA^J", "PSA^K", "PSA^L", "PSA^M", "PSA^N", "PSA^O", "PSA^P", "PSA^Q", "PSA^R", "PSA^S",
             "PSBD", "PSEC^A", "PSF", "PSFE", "PSN", "PSO", "PSQH", "PSTG", "PSTL", "PSX", "PTA", "PTY", "PUK", "PUMP",
             "PVH", "PVL", "PWR", "PWSC", "PX", "PYN", "PYT", "PZC", "QBTS", "QD", "QGEN", "QS", "QSR", "QTWO", "QUAD",
             "QVCC", "QVCD", "R", "RA", "RACE", "RAMP", "RBA", "RBC", "RBCP", "RBLX", "RBOT", "RBRK", "RBT", "RC",
             "RC^C",
             "RC^E", "RCB", "RCC", "RCFA", "RCI", "RCL", "RCS", "RCUS", "RDDT", "RDN", "RDW", "RDY", "RELX", "RERE",
             "RES",
             "REVG", "REX", "REXR", "REXR^B", "REXR^C", "REZI", "RF", "RF^B", "RF^C", "RF^E", "RFI", "RFL", "RFM",
             "RFMZ",
             "RGA", "RGR", "RGT", "RH", "RHI", "RHP", "RIG", "RIO", "RITM", "RITM^A", "RITM^B", "RITM^C", "RITM^D",
             "RIV",
             "RIV^A", "RJF", "RJF^B", "RKT", "RL", "RLI", "RLJ", "RLJ^A", "RLTY", "RLX", "RM", "RMAX", "RMD", "RMI",
             "RMM",
             "RMMZ", "RMPL^", "RMT", "RNG", "RNGR", "RNP", "RNR", "RNR^F", "RNR^G", "RNST", "ROG", "ROK", "ROL", "RPM",
             "RQI", "RRAC", "RRC", "RRX", "RS", "RSF", "RSG", "RSI", "RSKD", "RTO", "RTX", "RVLV", "RVT", "RVTY", "RWT",
             "RWT^A", "RWTN", "RXO", "RY", "RYAM", "RYAN", "RYI", "RYN", "RZB", "RZC", "S", "SA", "SABA", "SAFE", "SAH",
             "SAJ", "SAM", "SAN", "SAND", "SAP", "SAR", "SAT", "SAVE", "SAY", "SAZ", "SB", "SB^C", "SB^D", "SBBA",
             "SBH",
             "SBI", "SBOW", "SBR", "SBS", "SBSW", "SBXC", "SCCO", "SCD", "SCE^G", "SCE^H", "SCE^J", "SCE^K", "SCE^L",
             "SCE^M", "SCHW", "SCHW^D", "SCHW^J", "SCI", "SCL", "SCM", "SCS", "SCX", "SD", "SDHC", "SDHY", "SDRL", "SE",
             "SEAL^A", "SEAL^B", "SEDA", "SEE", "SEM", "SEMR", "SES", "SF", "SF^B", "SF^C", "SF^D", "SFB", "SFBS",
             "SFL",
             "SG", "SGHC", "SGU", "SHAK", "SHCO", "SHEL", "SHG", "SHO", "SHO^H", "SHO^I", "SHOP", "SHW", "SID", "SIG",
             "SII",
             "SITC", "SITC^A", "SITE", "SIX", "SJM", "SJT", "SJW", "SKE", "SKIL", "SKLZ", "SKM", "SKT", "SKX", "SKY",
             "SLB",
             "SLCA", "SLF", "SLG", "SLG^I", "SLGN", "SLQT", "SLVM", "SM", "SMAR", "SMBK", "SMFG", "SMG", "SMHI", "SMLP",
             "SMP", "SMR", "SMRT", "SMWB", "SN", "SNA", "SNAP", "SNDA", "SNDR", "SNN", "SNOW", "SNV", "SNV^D", "SNV^E",
             "SNX", "SO", "SOC", "SOI", "SOJC", "SOJD", "SOJE", "SOL", "SOLV", "SON", "SONY", "SOR", "SOS", "SPB",
             "SPCE",
             "SPE", "SPE^C", "SPG", "SPG^J", "SPGI", "SPH", "SPHR", "SPIR", "SPLP", "SPLP^A", "SPNT", "SPNT^B", "SPOT",
             "SPR", "SPRU", "SPXC", "SPXX", "SQ", "SQM", "SQNS", "SQSP", "SR", "SR^A", "SRE", "SREA", "SRFM", "SRG",
             "SRG^A",
             "SRI", "SRL", "SRV", "SSB", "SSD", "SSL", "SST", "SSTK", "ST", "STAG", "STC", "STE", "STEL", "STEM",
             "STEW",
             "STG", "STK", "STLA", "STM", "STN", "STNG", "STR", "STT", "STT^G", "STVN", "STWD", "STZ", "SU", "SUI",
             "SUM",
             "SUN", "SUP", "SUPV", "SUZ", "SVV", "SWI", "SWK", "SWN", "SWX", "SWZ", "SXC", "SXI", "SXT", "SYF", "SYF^A",
             "SYF^B", "SYK", "SYY", "T", "T^A", "T^C", "TAC", "TAK", "TAL", "TALO", "TAP", "TARO", "TBB", "TBBB", "TBC",
             "TBI", "TCI", "TCOA", "TCS", "TD", "TDC", "TDCX", "TDF", "TDG", "TDOC", "TDS", "TDS^U", "TDS^V", "TDW",
             "TDY",
             "TEAF", "TECK", "TEF", "TEI", "TEL", "TEO", "TEVA", "TEX", "TFC", "TFC^I", "TFC^O", "TFC^R", "TFII",
             "TFPM",
             "TFSA", "TFX", "TG", "TGI", "TGLS", "TGNA", "TGS", "TGT", "THC", "THG", "THO", "THQ", "THR", "THS", "THW",
             "TIMB", "TISI", "TIXT", "TJX", "TK", "TKC", "TKO", "TKR", "TLK", "TLYS", "TM", "TME", "TMHC", "TMO", "TNC",
             "TNET", "TNK", "TNL", "TNP", "TNP^E", "TNP^F", "TOL", "TOST", "TPB", "TPC", "TPH", "TPL", "TPR", "TPTA",
             "TPVG",
             "TPX", "TPZ", "TR", "TRAK", "TRC", "TREX", "TRGP", "TRI", "TRIS", "TRN", "TRNO", "TROX", "TRP", "TRTL",
             "TRTN^A", "TRTN^B", "TRTN^C", "TRTN^D", "TRTN^E", "TRTX", "TRTX^C", "TRU", "TRV", "TS", "TSE", "TSI",
             "TSLX",
             "TSM", "TSN", "TSQ", "TT", "TTC", "TTE", "TTI", "TTP", "TU", "TUP", "TUYA", "TV", "TVC", "TVE", "TWI",
             "TWLO",
             "TWN", "TWO", "TWO^A", "TWO^B", "TWO^C", "TX", "TXO", "TXT", "TY", "TY^", "TYG", "TYL", "U", "UA", "UAA",
             "UAN",
             "UBER", "UBS", "UDR", "UE", "UFI", "UGI", "UGIC", "UGP", "UHAL", "UHS", "UHT", "UI", "UIS", "UL", "ULS",
             "UMC",
             "UMH", "UMH^D", "UNF", "UNFI", "UNH", "UNM", "UNMA", "UNP", "UP", "UPS", "URI", "USA", "USAC", "USB",
             "USB^A",
             "USB^H", "USB^P", "USB^Q", "USB^R", "USB^S", "USFD", "USM", "USNA", "USPH", "UTF", "UTI", "UTL", "UTZ",
             "UVE",
             "UVV", "UWMC", "UZD", "UZE", "UZF", "V", "VAC", "VAL", "VALE", "VATE", "VBF", "VCV", "VEEV", "VEL", "VET",
             "VFC", "VGI", "VGM", "VGR", "VHC", "VHI", "VICI", "VIK", "VIPS", "VIST", "VIV", "VKQ", "VLD", "VLN", "VLO",
             "VLRS", "VLT", "VLTO", "VMC", "VMI", "VMO", "VNCE", "VNO", "VNO^L", "VNO^M", "VNO^N", "VNO^O", "VNT",
             "VOC",
             "VOYA", "VOYA^B", "VPG", "VPV", "VRE", "VRN", "VRT", "VRTS", "VSCO", "VSH", "VST", "VSTO", "VSTS", "VTEX",
             "VTLE", "VTMX", "VTN", "VTOL", "VTR", "VTS", "VVI", "VVR", "VVV", "VVX", "VYX", "VZIO", "W", "WAB", "WAL",
             "WAL^A", "WAT", "WBS", "WBS^F", "WBS^G", "WBX", "WCC", "WCC^A", "WCN", "WD", "WDH", "WDI", "WDS", "WEA",
             "WEAV",
             "WEC", "WEL", "WELL", "WES", "WEX", "WF", "WFC", "WFC^A", "WFC^C", "WFC^D", "WFC^L", "WFC^Y", "WFC^Z",
             "WFG",
             "WGO", "WH", "WHD", "WHG", "WHR", "WIA", "WIT", "WIW", "WK", "WKC", "WLK", "WLKP", "WLY", "WLYB", "WM",
             "WMB",
             "WMK", "WMS", "WMT", "WNC", "WNS", "WOLF", "WOR", "WOW", "WPC", "WPM", "WPP", "WRB", "WRB^E", "WRB^F",
             "WRB^G",
             "WRB^H", "WRBY", "WRK", "WS", "WSM", "WSO", "WSO/B", "WSR", "WST", "WT", "WTI", "WTM", "WTRG", "WTS",
             "WTTR",
             "WU", "WWW", "WY", "X", "XFLT", "XFLT^A", "XHR", "XIN", "XOM", "XPER", "XPEV", "XPO", "XPOF", "XPRO",
             "XYF",
             "XYL", "YALA", "YELP", "YETI", "YEXT", "YMM", "YOU", "YPF", "YRD", "YSG", "YUM", "YUMC", "ZBH", "ZEPP",
             "ZETA",
             "ZGN", "ZH", "ZIM", "ZIP", "ZK", "ZKH", "ZTO", "ZTR", "ZTS", "ZUO", "ZVIA", "ZWS"]
