name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event.before == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase login:ci --token $FIREBASE_TOKEN

    - name: Deploy to Firebase
      run: firebase deploy --only functions